### ISSUE TITLE
Choice with boolean occurence problem

### ISSUE THREAD

**Issue by akbence** [i-Cell-Mobilsoft-Open-Source/swagger-jaxb#8]
##  Explaining the problem

Consider, we have the following XSD:
```xml
            <xs:choice>
                <xs:element name="somebool" type="xs:boolean">
                    <xs:annotation>
                        <xs:documentation xml:lang="en">TESTBOOL</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="someBool2" type="xs:boolean">
                    <xs:annotation>
                        <xs:documentation xml:lang="en">TESTBOOL2</xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:choice>

```
With this snippet the following openapi document is generated:

```
        somebool:
          title: somebool
          description: TESZTBOOOL
          type: boolean
        someBool2:
          title: someBool2
          description: TESZTBOOL2
          type: boolean

```

When there is an <xs:choice> </xs:choice> field declared, the openapi shows, that either values are part of the structure, which is a false statement, in the view of validation. It is a limitation, therefore it needs a fix.

## Workaround

In this example, there is a workaround. If the openapi, could show, that _somebool_ could be either null, or a valid value, that would be a better solution, than this, right now. If we add _minOccurs="0"_ to the element, we could extract that to use it as a new property: nullable:false/true

In this situation (with the bool element) it would show the following:

```
        somebool:
          title: somebool
          description: TESZTBOOOL
          type: boolean
          nullable: true
        someBool2:
          title: someBool2
          description: TESZTBOOL2
          type: boolean
          nullable: true
```

```java
protected void addNullableProperty(JAnnotationUse apiProperty, CClassInfo targetClass, String propertyName) {
        CPropertyInfo property = targetClass.getProperty(propertyName);
        XSComponent schemaComponent = property.getSchemaComponent();
        if (schemaComponent instanceof XSParticle) {
            XSParticle particle = (XSParticle) schemaComponent;
            BigInteger minOccurs = particle.getMinOccurs();
            if (minOccurs.equals(BigInteger.ZERO)) {
                apiProperty.param(SchemaFields.NULLABLE, true);
            }
        }
    }
```

It is a workaround only, because the requirement can be, that either value have to be there, and this XSD says, it wont.
It is not the best solution, it needs a deeper research

## Best solution

If there would be a way, to extract, if an XSParticle is a part of choice, then there can be a new property (or the _nullable_), to tell it is in a XOR relation with the other part(s) of the choice.

Important note: Despite the issue's name, this problem is not unique to boolean's only.
